[simulation]
  name = "massive_a0995"
  engine = "grpic"
  runtime = 2000.0

[grid]
  resolution = [512, 512]
  extent = [[0.9, 15.0]]

  [grid.metric]
    metric = "kerr_schild"
    qsph_r0 = 0.0 
    qsph_h = 0.0
    ks_a = 0.0

  [grid.boundaries]
    fields = [["ABSORB"]]
    particles = [["ABSORB"]]

    [grid.boundaries.absorb]
      ds = 0.5

[scales]
  larmor0 = 2e-3
  skindepth0 = 0.1

[algorithms]
  current_filters = 4

  [algorithms.gr]
    pusher_niter = 10
    pusher_eps = 1e-10

  [algorithms.timestep]
    CFL = 6.0

  [algorithms.toggles]
    deposit = false
    fieldsolver = false

[particles]
  ppc0 = 4.0

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = 0.0
  maxnpart = 1e1

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 0.0
  maxnpart = 1e1

[setup]
  # (2,3,1) from Levin&Perez-Giz (2008)
  x1s  = [10.343515586064923]
  y1s  = [1.570796]
  z1s  = [0.000000]
  ux1s = [0.19483849893499136]
  uy1s = [0.000000]
  uz1s = [2.000000]

  # (~1000, 3, ~671) from Levin&Perez-Giz (2008)
  x2s  = [10.64975354]
  y2s  = [1.570796]
  z2s  = [0.000000]
  ux2s = [0.18914503]
  uy2s = [0.000000]
  uz2s = [2.000000]

[output]
  format = "hdf5"

  [output.fields]
    enable = true
    interval_time = 5.0
    quantities = ["D", "B"]

  [output.particles]
    enable = true
    stride = 1
    interval_time = 2.0
    species = []

  [output.spectra]
    enable = false

[diagnostics]
  interval = 10
  colored_stdout = true
  blocking_timers = true
