[simulation]
  name = "massive_a0"
  engine = "grpic"
  runtime = 500.0

[grid]
  resolution = [256,256]
  extent = [[1.2, 15.0]]

  [grid.metric]
    metric = "qkerr_schild"
    qsph_r0 = 0.0 
    qsph_h = 0.0
    ks_a = 0.0

  [grid.boundaries]
    fields = [["ABSORB"]]
    particles = [["ABSORB"]]

    [grid.boundaries.absorb]
      ds = 0.5

[scales]
  larmor0 = 2e-3
  skindepth0 = 0.1

[algorithms]
  current_filters = 4

  [algorithms.gr]
    pusher_niter = 10
    pusher_eps = 1e-3

  [algorithms.timestep]
    CFL = 0.8

  [algorithms.toggles]
    deposit = false
    fieldsolver = false

[particles]
  ppc0 = 4.0

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = 0.0
  maxnpart = 1e1

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 0.0
  maxnpart = 1e1

[setup]
  # (1,2,0) from Levin&Perez-Giz (2008)
  x1s  = [9.85180645]
  y1s  = [1.570796]
  z1s  = [0.5235987755982988]
  ux1s = [0.24159816]
  uy1s = [3.535534]
  uz1s = [0.000000]

  # (4,1,1) from Levin&Perez-Giz (2008)
  x2s  = [68.600387]
  y2s  = [1.570796]
  z2s  = [0.000000]
  ux2s = [0.029637]
  uy2s = [0.000000]
  uz2s = [3.900000]

[output]
  format = "hdf5"

  [output.fields]
    enable = true
    interval_time = 1.0
    quantities = ["D", "B"]

  [output.particles]
    enable = true
    stride = 1
    interval_time = 1.0
    species = []

  [output.spectra]
    enable = false

[diagnostics]
  interval = 10
  colored_stdout = true
  blocking_timers = true
