[simulation]
title           = "Example"
runtime         = 0.1

[domain]
resolution      = [512, 512]
extent          = [-2.0, 2.0, -2.0, 2.0]
boundaries      = ["PERIODIC", "PERIODIC"]

[algorithm]
CFL             = 0.5
correction      = 1.0

[units]
ppc0            = 0.1
larmor0         = 0.1
skindepth0      = 0.01

[problem]
amplitude       = 2.5
nx1             = 5
nx2             = 5

[visualization]
fields          = ["Bx", "By", "Bz", "Ex", "Ey", "Ez", "Jx", "Jy", "Jz"]