[simulation]
title           = "Polar_example"
runtime         = 0.1

[domain]
qsph_r0         = 0.0
qsph_h          = 0.001
sph_rabsorb     = 9.0
resolution      = [256, 128]
extent          = [1.0, 10.0]
boundaries      = ["USER", "USER"]

[algorithm]
CFL             = 0.9
correction      = 1.0

[units]
ppc0            = 0.1
larmor0         = 0.1
skindepth0      = 0.01

[visualization]
fields          = ["Br", "Btheta", "Bphi", 
                   "Er", "Etheta", "Ephi"]