[simulation]
title           = "Boris example"
runtime         = 0.1

[domain]
resolution      = [64, 64]
extent          = [-2.0, 2.0, -2.0, 2.0]
boundaries      = ["PERIODIC", "PERIODIC"]

[algorithm]
CFL             = 0.1
correction      = 1.0
#fieldsolver_ON  = true
#deposit_ON      = false

[units]
ppc0            = 0.1
larmor0         = 0.5
skindepth0      = 0.5

[particles]
n_species       = 3

[species_1]
label           = "electron"
mass            = 1.0
charge          = -1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_2]
label           = "positron"
mass            = 1.0
charge          = 1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_3]
label           = "photon"
mass            = 0.0
charge          = 0.0
maxnpart        = 1e2
pusher          = "Photon"

[problem]

[visualization]
fields          = ["Bx", "By", "Bz", "Ex", "Ey", "Ez", "Jx", "Jy", "Jz"]
